### ISSUE TITLE
Slice out of range error

### ISSUE THREAD

**Issue by ajnavarro** [src-d/enry#129] opened 2017-11-08 09:57 UTC
Calling to `GetLanguage` method, sometimes we receive this error:

panic: runtime error: slice bounds out of range
goroutine 17 [running, locked to thread]:
bytes.Count(0x7f627818c0d0, 0x4b, 0x0, 0x1c420038c20, 0x1, 0x20, 0x0)
    /home/travis/.gimme/versions/go1.8.linux.amd64/src/bytes/bytes.go:62 +0x21d
gopkg.in/src-d/enry%2ev1.getHeaderAndFooter(0x7f627818c0d0, 0x4b, 0x0, 0x0, 0x0, 0x0)
    /home/travis/gopath/src/gopkg.in/src-d/enry.v1/common.go:161 +0x9d
gopkg.in/src-d/enry%2ev1.GetLanguagesByModeline(0x7f627818f4a0, 0x0, 0x7f627818c0d0, 0x4b, 0x0, 0x7f62482e6c08, 0x0, 0x0, 0x0, 0x0, ...)
    /home/travis/gopath/src/gopkg.in/src-d/enry.v1/common.go:142 +0x5c
gopkg.in/src-d/enry%2ev1.GetLanguages(0x7f627818f4a0, 0x0, 0x7f627818c0d0, 0x4b, 0x0, 0x0, 0x0, 0x0)
    /home/travis/gopath/src/gopkg.in/src-d/enry.v1/common.go:126 +0x129
gopkg.in/src-d/enry%2ev1.GetLanguage(0x7f627818f4a0, 0x0, 0x7f627818c0d0, 0x4b, 0x0, 0x1c420038e48, 0x1c42001a500)
    /home/travis/gopath/src/gopkg.in/src-d/enry.v1/common.go:38 +0x55
main.GetLanguage(0x7f627818f4a0, 0x0, 0x7f627818c0d0, 0x4b, 0x0, 0x0, 0x0)
    /home/travis/build/src-d/enry/shared/enry.go:11 +0x55
main._cgoexpwrap_f7db11756761_GetLanguage(0x7f627818f4a0, 0x0, 0x7f627818c0d0, 0x4b, 0x0, 0x0, 0x0)
    command-line-arguments/_obj/_cgo_gotypes.go:58 +0x9a

**Comment by mcarmonaa** [comment] 2017-11-08 10:03
@ajnavarro how can I reproduce it?

**Comment by ajnavarro** [comment] 2017-11-08 10:46
I would try to send to `GetLanguagesByModeline` an empty or nil `content` param.

**Comment by mcarmonaa** [comment] 2017-11-08 11:03
Enry already has a test with nil content, as you can see [here](https://github.com/src-d/enry/blob/master/common_test.go#L79). It's for the general functions `GetLanguage`, but `GetLanguagesByModeline` is the firs strategy to run, so it should raise a fail if any problem.

Anyway, I added a couple of cases with `nil` and `[]byte{}` as content to the test `TestGetLanguagesByModeline` and they pass without problems.

There is a weird thing, the function where the process is raising a panic (`bytes.Count`) works well with `nil` or `[]byte{]` content, demonstration [here](https://play.golang.org/p/ejkf38kITU)

For the moment, I couldn't reproduce the panic in local.

Keep on it.

**Comment by mcarmonaa** [comment] 2017-11-08 12:43
Eventually I couldn't reproduce the panic, so I didn't check if #130 fix the problem at all.

About the previous comment, some other things should be known about this issue:
- `bytes.Count()` function implementation depends on the platform it's running on. You can found these differences under `$GOROOT/src/bytes` in files `bytes.go`,`bytes_generic.go`,`bytes_amd64.go`,`bytes_s390x.go`
- Currently travis it's using go version `1.8`, I changed it to `1.8.x` to use the latest minor release of this version. Maybe it would fix something.
- Another weird behavior from `bytes.Count()`, `sep` argument it's always required except if `s` is nil. In that case, the function returns `1`, [check out here](https://play.golang.org/p/Se2_JCje6p)

Anyway, PR #130 try to fix this checking for empty or nil content before call `bytes.Count()` function

**Comment by vmarkovtsev** [comment] 2017-11-10 11:47
I can reproduce it too and it blocks us.

```
panic: runtime error: slice bounds out of range

goroutine 17 [running, locked to thread]:
bytes.Count(0x7f23e02849b0, 0xa, 0x0, 0x1c42003cc20, 0x1, 0x20, 0x0)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/bytes/bytes.go:62 +0x21d
gopkg.in/src-d/enry%2ev1.getHeaderAndFooter(0x7f23e02849b0, 0xa, 0x0, 0x66, 0x6, 0x7f23b80bc5f0)
	/home/travis/gopath/src/gopkg.in/src-d/enry.v1/common.go:161 +0x9d
gopkg.in/src-d/enry%2ev1.GetLanguagesByModeline(0x7f23e02f4710, 0x2, 0x7f23e02849b0, 0xa, 0x0, 0x7f23b99cdc08, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/gopkg.in/src-d/enry.v1/common.go:142 +0x5c
gopkg.in/src-d/enry%2ev1.GetLanguages(0x7f23e02f4710, 0x2, 0x7f23e02849b0, 0xa, 0x0, 0x7f23b8ef9a73, 0xc, 0x1c420020de0)
	/home/travis/gopath/src/gopkg.in/src-d/enry.v1/common.go:126 +0x129
gopkg.in/src-d/enry%2ev1.GetLanguage(0x7f23e02f4710, 0x2, 0x7f23e02849b0, 0xa, 0x0, 0x1c42003ce48, 0x1c420016f00)
	/home/travis/gopath/src/gopkg.in/src-d/enry.v1/common.go:38 +0x55
main.GetLanguage(0x7f23e02f4710, 0x2, 0x7f23e02849b0, 0xa, 0x0, 0x1c42001a1d8, 0x1c4200007e0)
	/home/travis/build/src-d/enry/shared/enry.go:11 +0x55
main._cgoexpwrap_f7db11756761_GetLanguage(0x7f23e02f4710, 0x2, 0x7f23e02849b0, 0xa, 0x0, 0x0, 0x0)
	command-line-arguments/_obj/_cgo_gotypes.go:58 +0x9a
panic: runtime error: slice bounds out of range
```

I will try to reproduce it because I am desperate and cannot work forward.

**Comment by abeaumont** [comment] 2017-11-10 11:55
I've just released [v1.6.0](https://github.com/src-d/enry/releases/tag/v1.6.0), which includes #130. Check if the error is solved with this release.

**Comment by vmarkovtsev** [comment] 2017-11-10 11:56
@ajnavarro I think it makes sense to allow enry crash and just skip the corresponding file, recording it to the errors list together with stderr output. E.g. we used to do it in our Python pipeline.

**Comment by vmarkovtsev** [comment] 2017-11-10 12:08
@abeaumont I confirm that there is no panic with the latest release.

**Comment by abeaumont** [comment] 2017-11-10 12:11
great, closing then.

**Comment by EgorBu** [comment] 2017-12-07 14:05
Hi,

it looks like that this issue still exists. It appears quite rarely, so it should be tricky to debug.
https://github.com/src-d/engine/issues/243
should a new issue be created? Or reopen this?

@abeaumont , @mcarmonaa , what do you think?

**Comment by vmarkovtsev** [comment] 2017-12-07 14:17
@egorbu You need to prove that Engine uses the updated version. When I used to have similar issues, I ran Engine locally, without a container, and replaced libenry.so in the engine's JAR with the manually built binary. And for sure in that case you need to prove that your patched JAR is used - sometimes Maven decides to overwrite it.

**Comment by EgorBu** [comment] 2017-12-07 14:22
@vmarkovtsev , from https://github.com/src-d/engine/issues/243#issuecomment-349267539 - it should be enry  1.6.1

**Comment by abeaumont** [comment] 2017-12-07 14:28
The issue can be reopened if needed. Do you have a file sample causing the crash? Does the problem also happen when enry cli is used?

**Comment by EgorBu** [comment] 2017-12-07 14:35
@abeaumont , unfortunately - no. Because it rarely happens. Most of the times - everything works well, and sometimes it fails.
If you may tell which information could be useful for debugging - I may try to find way how to collect it

**Comment by abeaumont** [comment] 2017-12-07 14:47
Even if frequency is low, it must happen with some file... that would be best information for debugging. Apart from that, an updated stack trace would also help.

**Comment by EgorBu** [comment] 2017-12-07 14:57
Do you want stack trace like in https://github.com/src-d/engine/issues/243#issue-278961577 ? Or something else?
BTW - does some kind of `DEBUG` version of `enry` exist? I may try to modify `jar` as @vmarkovtsev  mentioned in https://github.com/src-d/enry/issues/129#issuecomment-349979513

**Comment by abeaumont** [comment] 2017-12-07 15:12
@EgorBu yes, that one. Apparently you're passing an empty filename and that's causing the problem. I'll fix enry to avoid that crash, you may want to workaround it by filtering files without name in the meantime.

**Comment by EgorBu** [comment] 2017-12-07 15:26
Interesting that it works most of the times if it always should be empty

**Comment by vmarkovtsev** [comment] 2017-12-07 16:18
We can hit two different problems here: breaking on empty filenames and the engine probabilistically supplying empty file names due to some crazy race or whatever.

**Comment by EgorBu** [comment] 2017-12-11 09:36
sounds reasonable.
What do you think, @ajnavarro? Can it happen?

**Closed** 2017-12-12 09:34 UTC
