### ISSUE TITLE
Surprising programming languages

### ISSUE THREAD

**Issue by campoy** [src-d/enry#148] opened 2018-05-10 23:19 UTC
I decided to list all of the languages that appear in Public Git Archive and I got a couple of surprising results.

Some of the results:
- desktop
- Regular Expression
- Raw token data
- Public Key
- HTTP
- NumPy

Any of these results above are technically languages, some are protocol, some are libraries, some are ... something else completely!

Should we add a clarification regarding these? I think it'd be interesting to have it for Public Git Archive, currently I get over 455 languages, but I suspect some of them are not technically languages.

**Comment by dennwc** [comment] 2018-05-11 00:50
FYI https://github.com/src-d/enry/pull/139 added a flag to only check for programming languages, if it helps

**Comment by mcarmonaa** [comment] 2018-05-11 06:33
Basically, the languages enry recognizes are those present in this [yaml file](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml) from linguist, which we parse to generate our data.

`Languages` doesn't mean programming languages. The handled languages can be of [different types](https://github.com/src-d/enry/blob/master/common.go#L430): data, programming, markup, prose, or unknown.

As @dennwc said, it seems that the cli has a [flag](https://github.com/src-d/enry/blob/master/cmd/enry/main.go#L116) now to show only those languages of type `programming`

**Comment by smola** [comment] 2018-08-03 09:08
Closing, since this works as intended. Language type can be checked with `data.LanguageType`.

**Closed by smola** 2018-08-03 09:08 UTC
Labels: question
